Update nightly_backup

diff --git a/nextcloud/nimbus/nightly_backup b/nextcloud/nimbus/nightly_backup
--- a/nextcloud/nimbus/nightly_backup
+++ b/nextcloud/nimbus/nightly_backup
@@ -1,24 +1,24 @@
 #!/usr/bin/env bash
 
 [ "$EUID" -ne 0 ] && {
-	echo "Error: Must be root." >&2
-	exit 1
+        echo "Error: Must be root." >&2
+        exit 1
 }
 
-NC_DIR='/var/www/nextcloud'
-DATA_DIR='/data/nextcloud'
-BACKUP_DIR='/backup/nextcloud/nightly'
-DB_NAME='nextcloud_db'
+BACKUP_DIR='/backup/nightly'
 
-# Prevents corruption
-sudo -u www-data php $NC_DIR/occ maintenance:mode --on
+# Nextcloud
+NC_INSTALL_DIR='/var/www/nextcloud'
+NC_DATA_DIR='/data/nextcloud'
+NC_DB_NAME='nextcloud_db'
 
-# Backs up config, data and themes
-rsync -Aavx $NC_DIR/config $DATA_DIR $NC_DIR/themes $BACKUP_DIR/
+sudo -u www-data php $NC_INSTALL_DIR/occ maintenance:mode --on
+rsync -Aavx $NC_INSTALL_DIR/config $NC_DATA_DIR $NC_INSTALL_DIR/themes $BACKUP_DIR/nextcloud/
+mysqldump --single-transaction --default-character-set=utf8mb4 $NC_DB_NAME > $BACKUP_DIR/nextcloud/sql_backup
+sudo -u www-data php $NC_INSTALL_DIR/occ maintenance:mode --off
 
-# Backs up the database (contacts, calendar...)
-mysqldump --single-transaction --default-character-set=utf8mb4 $DB_NAME > $BACKUP_DIR/sql_backup
-
-sudo -u www-data php $NC_DIR/occ maintenance:mode --off
+# Users
+USERS_DIR='/data/users'
+rsync -Aavx $USERS_DIR $BACKUP_DIR/
 
 exit
